### ISSUE TITLE
エラーメッセージ

### ISSUE THREAD

**Issue by ghost** [EC-site-TeamSmile/nagano_cake#58]
<img width="1440" alt="スクリーンショット 2021-05-21 16 08 04" src="https://user-images.githubusercontent.com/78802217/119096604-c0375800-ba4e-11eb-829f-43ce76d5f1bb.png">

エラーメッセージが出る際に、自分たちで書いたエラーメッセージだと英語のカラム名と日本語のメッセージがごっちゃに出てきて違和感があるので、エラーメッセージの日本語化をしてみてはどうでしょうか？

参考サイト
https://qiita.com/Ushinji/items/242bfba84df7a5a67d5b

**Comment by haaanyan** [comment]
やってみます〜！
